name: Outbound Email Engine

on:
  repository_dispatch:
    types: [send_email_event]

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email using Native Ubuntu Mail
        run: |
          # استقبال البيانات القادمة من كلود فلير
          TO="${{ github.event.client_payload.to }}"
          SUBJECT="${{ github.event.client_payload.subject }}"
          HTML_BODY="${{ github.event.client_payload.html }}"
          
          # تثبيت أداة الإرسال الأصلية لنظام لينكس سريعا
          sudo apt-get update && sudo apt-get install -y mailutils
          
          # قذف الرسالة فوراً عبر خوادم السحابة الحرة لـ Ubuntu إلى الـ Inbox الخارجي
          echo "$HTML_BODY" | mail -a "Content-Type: text/html; charset=UTF-8" -s "$SUBJECT" "$TO"
